### ISSUE TITLE
Object.hasOwn is not a function Bug

### ISSUE THREAD

**Issue by sinisterrook** [ProfessorManhattan/semantic-release-python#1]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

## Description

Essentially the plugin fails to after the verification step with Object.hasOwn is not a function.

## Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

__Error Log__
```
[8:09:06 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "semantic-release-python"
[8:09:06 PM] [semantic-release] › ✖  Failed step "verifyConditions" of plugin "semantic-release-python"
[8:09:06 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/exec"
[8:09:06 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/exec"
[8:09:06 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/changelog"
[8:09:06 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/changelog"
[8:09:06 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/git"
[8:09:06 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/git"
[8:09:06 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/gitlab"
[8:09:06 PM] [semantic-release] [@semantic-release/gitlab] › ℹ  Verify GitLab authentication (https://gitlab.com/api/v4)
[8:09:06 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/gitlab"
[8:09:06 PM] [semantic-release] › ✖  An error occurred while running semantic-release: TypeError: Object.hasOwn is not a function
    at getOption (/builds/lmco/hoppr/hoppr/node_modules/semantic-release-python/lib/util.js:10:17)
    at verifyPoetry (/builds/lmco/hoppr/hoppr/node_modules/semantic-release-python/lib/verify.js:123:23)
    at verify (/builds/lmco/hoppr/hoppr/node_modules/semantic-release-python/lib/verify.js:149:11)
    at validator (/opt/node_modules/semantic-release/lib/plugins/normalize.js:34:30)
    at /opt/node_modules/semantic-release/lib/plugins/pipeline.js:37:40
    at next (/opt/node_modules/p-reduce/index.js:17:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  pluginName: 'semantic-release-python'
}
AggregateError: 
    TypeError: Object.hasOwn is not a function
        at getOption (/builds/lmco/hoppr/hoppr/node_modules/semantic-release-python/lib/util.js:10:17)
        at verifyPoetry (/builds/lmco/hoppr/hoppr/node_modules/semantic-release-python/lib/verify.js:123:23)
        at verify (/builds/lmco/hoppr/hoppr/node_modules/semantic-release-python/lib/verify.js:149:11)
        at validator (/opt/node_modules/semantic-release/lib/plugins/normalize.js:34:30)
        at /opt/node_modules/semantic-release/lib/plugins/pipeline.js:37:40
        at next (/opt/node_modules/p-reduce/index.js:17:9)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at /opt/node_modules/semantic-release/lib/plugins/pipeline.js:54:11
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.pluginsConf.<computed> [as verifyConditions] (/opt/node_modules/semantic-release/lib/plugins/index.js:80:11)
    at async run (/opt/node_modules/semantic-release/index.js:95:3)
    at async module.exports (/opt/node_modules/semantic-release/index.js:260:22)
    at async module.exports (/opt/node_modules/semantic-release/cli.js:55:5)
```

**Comment by iamjohnnym** [comment]
Any work arounds or when this issue might be resolved?
